return { -- Which-key
    'folke/which-key.nvim',
    event = 'VimEnter',
    opts = {
        delay = 0,
        icons = {
            mappings = vim.g.have_nerd_font,
            keys = vim.g.have_nerd_font and {} or {
                Up = '<Up> ',
                Down = '<Down> ',
                Left = '<Left> ',
                Right = '<Right> ',
                C = '<C-…> ',
                M = '<M-…> ',
                D = '<D-…> ',
                S = '<S-…> ',
                CR = '<CR> ',
                Esc = '<Esc> ',
                Space = '<Space> ',
                Tab = '<Tab> ',
                F1 = '<F1>',
                F2 = '<F2>',
                F3 = '<F3>',
                F4 = '<F4>',
                F5 = '<F5>',
                F6 = '<F6>',
                F7 = '<F7>',
                F8 = '<F8>',
                F9 = '<F9>',
                F10 = '<F10>',
                F11 = '<F11>',
                F12 = '<F12>',
            },
        },
        spec = {
            -- Git

            { '<leader>g',  group = '[G]it Suite' },
            { '<leader>gs', group = '[S]tage' },
            { '<leader>gc', group = '[C]ommit' },
            { '<leader>gp', group = '[P]ush' },
            { '<leader>gl', group = 'Pul[l]' },
            { '<leader>gr', group = '[R]eset' },
            { '<leader>gC', group = '[B]ranch' },
            { '<leader>gT', group = '[T]ag' },
            { '<leader>gy', group = 'Cherr[y]-pick' },
            { '<leader>gd', group = '[D]iff' },
            { '<leader>gt', group = 'S[t]ash' },
            { '<leader>gS', group = '[S]tatus' },
            { '<leader>gn', group = '[N]eogit' },
            { '<leader>gL', group = '[L]og' },
            --Other

            { '<leader>tt', group = 'Toggle [T]erminal' },
            { '<leader>c', group = 'Toggle [C]heckbox'},
            { '<leader>d', group = '[D]ebug Tools'},
            { '<leader>r', group = '[R]est'},
            { '<leader>z',  group = 'Ba[Z]el}' },
            { '<leader>T',  group = '[T]esting' },
            { '<leader>tN', group = '[N]eoCodeium Options' },
            { '<leader>tc', group = 'nvim-[c]mp options' },
            { '<leader>th', group = 'Toggle C[h]eckbox' },
            { '<leader>m',  group = '[M]ake C++ Build' },
            { '<leader>w',  group = '[W]orkspace' },
            { '<leader>o',  group = '[O]pen' },
            { '<leader>w',  group = '[W]orkspace' },
            { '<leader>M',  group = '[M]ini Map' },
            { '<leader>s',  group = '[S]earch' },
            { '<leader>t',  group = '[T]oggle' },
            { '<leader>h',  group = '[H]arpoon' },
        },
    },
}
